version: 2
jobs:
  build:
    working_directory: ~/mern-starter
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: alfredwhelan/dockerce:1.5
    steps:
      - checkout
      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t alfredwhelan/microservice02:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push alfredwhelan/microservice02:$TAG
          sed -i "s/microservice02:.*/microservice02:$TAG/g" k8s/microservice-deployment.yaml
          az login --service-principal -u $SPU -p $SPP --tenant $SPT
          az aks get-credentials --resource-group acctestRG1 --name acctestaks1
          kubectl apply -f k8s/microservice-deployment.yaml