#ELK deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice02-deployment
  labels:
    app: microservice02
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice02
  template:
    metadata:
      labels:
        app: microservice02
    spec:
      containers:
      - name: microservice02-service
        image: alfredwhelan/microservice02:1.0
        ports:
        - containerPort: 8001
---
kind: Service
apiVersion: v1
metadata:
  name: microservice02
spec:
  type: LoadBalancer
  selector:
    app: microservice02
  ports:
  - port: 80
    targetPort: 8001